### ISSUE TITLE
Problems with compiling 

### ISSUE THREAD

**Issue by Jordon87** [Joshua-Ashton/VTFLib#2]
So I've been trying to compile this for a while, however I keep getting these errors I can't really resolve. I am also using Visual Studio 2019 yeah.
![image](https://user-images.githubusercontent.com/38020644/134624754-3a6f2055-5b4f-4fff-8557-73d9016f7270.png)
The first error I could probably fix, but the second one's tricky. The HLLib.h file isn't even being compiled into a .Lib file and I don't understand why. I hope you can help with this.

**Comment by jessica945** [comment]
You'll have to grab the HLLib library yourself and put it in that directory. It's not included in the repository.
Header files don't get compiled into a library, it's just there so that VTFLib knows what HLLib does so that it can use it's exported functions.

Nem's page has been down for a while now, so you can grab it [from this mirror.](https://nemstools.github.io/subpages/Comments/HLLib.html).

**Comment by Jordon87** [comment]
Ah alright. Thanks then.
